# Generated by Django 6.0.4 on 2026-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='hardware_id',
        ),
        migrations.AddField(
            model_name='farm',
            name='current_moisture',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='farm',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='farm',
            name='name',
            field=models.CharField(default='My Farm', max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='pump_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(default='Puerto Princesa City', max_length=200),
        ),
    ]
