# Generated by Django 6.0.2 on 2026-04-24 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_farm_farmer_remove_farm_hardware_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='farm',
            name='current_ph',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='farm',
            name='current_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='is_raining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pumpcontrol',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='is_raining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ph_level',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
