# Generated by Django 6.0.4 on 2026-04-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sensordata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='current_moisture',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='current_ph',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='current_temp',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='is_raining',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='pump_status',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='farm',
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_moisture', models.FloatField(default=0.0)),
                ('current_ph', models.FloatField(default=7.0)),
                ('current_temp', models.FloatField(default=0.0)),
                ('is_raining', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('pump_status', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.farm')),
            ],
        ),
        migrations.AddField(
            model_name='sensordata',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='core.block'),
            preserve_default=False,
        ),
    ]
