# Generated by Django 6.0.4 on 2026-04-24 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_farm_current_moisture_remove_farm_current_ph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpcontrol',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='waterlog',
            name='farm',
        ),
        migrations.AddField(
            model_name='pumpcontrol',
            name='block',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pump_control', to='core.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterlog',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='core.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterlog',
            name='mode',
            field=models.CharField(default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='moisture_at_time',
            field=models.IntegerField(default=0),
        ),
    ]
