# Generated by Django 6.0.4 on 2026-04-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_farmerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='pin',
        ),
    ]
