# Generated by Django 6.0.4 on 2026-04-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lguprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lguprofile',
            name='full_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lguprofile',
            name='role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
