# Generated by Django 6.0.4 on 2026-04-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lguprofile_full_name_lguprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrocontrollerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_id', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(default='Arduino Node', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='core.block')),
            ],
        ),
    ]
