# Generated by Django 6.0.4 on 2026-04-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_microcontrollerdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MicrocontrollerDevice',
        ),
    ]
