# Generated by Django 6.0.4 on 2026-04-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_microcontrollerdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IrrigationSettings',
        ),
    ]
