# Generated by Django 6.0.4 on 2026-04-26 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_irrigationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farmer',
        ),
        migrations.AddField(
            model_name='farm',
            name='farmers',
            field=models.ManyToManyField(blank=True, related_name='farms', to=settings.AUTH_USER_MODEL),
        ),
    ]
