# Generated by Django 6.0.4 on 2026-04-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_farm_farmer_farm_farmers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='farmers',
            new_name='farmer',
        ),
    ]
