# Generated by Django 6.0.4 on 2026-04-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_farmers_farm_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='water_tank_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='water_tank_level',
            field=models.FloatField(default=0.0),
        ),
    ]
