# Generated by Django 6.0.4 on 2026-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_block_water_tank_level_sensordata_water_tank_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='critical_threshold',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='block',
            name='dry_threshold',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='block',
            name='wet_threshold',
            field=models.IntegerField(default=70),
        ),
    ]
