# Generated by Django 6.0.4 on 2026-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_block_critical_threshold_block_dry_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='farmer_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
